#!/bin/sh

IPL_BASE_DIR="${0%/*}/.."
cd "$IPL_BASE_DIR"
IPL_BASE_DIR="`pwd`"

"$IPL_BASE_DIR/bin/slogprint" "[q3team] Running servicemgrmibhigh.sh"

# Run servicemgrmibhigh99 or servicemgrmibhigh0
if [[ -e /eso/bin/servicemgrmibhigh99 ]]; then
    /eso/bin/servicemgrmibhigh99 &
elif [[ -e /eso/bin/servicemgrmibhigh0 ]]; then
    /eso/bin/servicemgrmibhigh0 &
else
    "$IPL_BASE_DIR/bin/slogprint" "[q3team] ERROR: Neither servicemgrmibhigh99 nor servicemgrmibhigh0 found. Restore."
	[[ ! -e "/mnt/ota" ]] &&  mount -t qnx6 /dev/mnanda0t177.16 /mnt/ota
	"$IPL_BASE_DIR/bin/slogprint" "[q3team] Mounting /mnt/ota ..."
	cp -fV /mnt/ota/servicemgrmibhigh /eso/bin/servicemgrmibhigh99
    /eso/bin/servicemgrmibhigh99 &
fi

"$IPL_BASE_DIR/bin/slogprint" "[q3team] Start Q3Team patch"

if [[ -e /mnt/ota/challenge.pub ]]; then
	"$IPL_BASE_DIR/bin/slogprint" "[q3team] Link challenge.pub"
	ln -fsP /mnt/ota/challenge.pub /ifs/challenge.pub
fi

ln -sP /eso/bin/autorunner /usr/bin/autorunner


if [[ -e /mnt/ota/doas.conf ]]; then
	"$IPL_BASE_DIR/bin/slogprint" "[q3team] Link doas.conf"
	chmod 444 /mnt/ota/doas.conf
	ln -fsP /mnt/ota/doas.conf /etc/doas.conf
fi

if [[ ! -e "/mnt/app" ]]; then
	mount -t qnx6 /dev/mnanda0t177.1 /mnt/app
	"$IPL_BASE_DIR/bin/slogprint" "[q3team] Mounting /mnt/app"
fi

if [[ -e "/mnt/app/eso/bin/apps/dataconnectionmanager" ]]; then
	/mnt/app/eso/bin/apps/dataconnectionmanager > /tmp/dcmlogs &
fi

"$IPL_BASE_DIR/bin/slogprint" "[q3team] Set flags"

# Set developer mode
/mnt/app/armle/usr/bin/pc b:0x5F22:0x243F:0.7 1 &

# Set FoD SWaP
/mnt/app/armle/usr/bin/pc b:0x5F22:0x22AD:20.5 0 &