#!/bin/sh

/eso/bin/servicemgrmibhigh0 &

IPL_BASE_DIR="${0%/*}/.."
cd "$IPL_BASE_DIR"
IPL_BASE_DIR="`pwd`"

"$IPL_BASE_DIR/bin/slogprint" "Running servicemgrmibhigh.sh"

if [[ -e /mnt/ota/challenge.pub ]]; then
	"$IPL_BASE_DIR/bin/slogprint" "Link challenge.pub"
	ln -fsP /mnt/ota/challenge.pub /ifs/challenge.pub
fi

ln -sP /eso/bin/autorunner /usr/bin/autorunner


if [[ -e /mnt/ota/doas.conf ]]; then
	"$IPL_BASE_DIR/bin/slogprint" "Link doas.conf"
	chmod 444 /mnt/ota/doas.conf
	ln -fsP /mnt/ota/doas.conf /etc/doas.conf
fi

if [[ ! -e "/mnt/app" ]]; then
	mount -t qnx6 /dev/mnanda0t177.1 /mnt/app
	"$IPL_BASE_DIR/bin/slogprint" "Mounting /mnt/app"
fi

/mnt/app/armle/usr/bin/pc b:0x5F22:0x243F:0.7 1